### ISSUE TITLE
General question: Update an email?

### ISSUE THREAD

**Issue by zebrastribe** [dhrechanyi/activecampaign-api-v3-wrapper#2]
Hi
Can your wrapper be used to update a contacts email?

**Comment by hrechanyi** [comment]
@zebrastribe
yes, it can. you should use `update` function
https://github.com/dhrechanyi/activecampaign-api-v3-wrapper#contacts

![Screenshot 1](https://user-images.githubusercontent.com/11639082/122084021-14451a80-ce0a-11eb-9eaa-0ae667027ac4.jpg)

**Comment by zebrastribe** [comment]
Cool. I will give it a try :)

**Comment by zebrastribe** [comment]
I get this error:

Client error: `PUT https://XXX.api-us1.com/contacts/50509` resulted in a `404 Not Found` response:
(truncated...)
